language: lisp
sudo: required

env:
  matrix:
    - LISP=abcl
    - LISP=allegro
    - LISP=sbcl
    - LISP=sbcl32
    - LISP=ccl
    - LISP=ccl32
    - LISP=clisp
    - LISP=clisp32
    - LISP=cmucl
    - LISP=ecl

matrix:
  allow_failures:
    - env: LISP=ccl32
    - env: LISP=cmucl

install:
  - curl -L https://github.com/luismbo/cl-travis/raw/master/install.sh | sh

script:
        - cl -e '(ql:quickload "deflate")'
